openapi: 3.0.2
info:
  title: 'Rest API для БД горных перевалов ФСТР, пополняемая туристами.'
  version: "0.1"

paths:
  /perevals:
    get:
      summary: Получение списка всех объектов Pereval
      operationId: listPerevals
      parameters:
        - in: query
          name: user__email
          schema:
            type: string


      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pereval'
          description: ''
      tags:
        - perevals

    post:
      summary: Создание объекта Pereval
      operationId: createPereval
      parameters:
        - in: body
          required: true
          name: data
          schema:
            $ref: '#/components/schemas/Pereval'

      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pereval'
          description: ''
      tags:
        - perevals

  /perevals/{id}:
    get:
      summary: Получение объекта Pereval по идентификатору
      operationId: getPerevalById
      parameters:
        - in: path
          required: true
          name: id
          schema:
            type: string
          description: id объекта Pereval

      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pereval'
          description: ''
      tags:
        - perevals

    patch:
      summary: Изменение объекта Pereval по идентификатору
      operationId: editPereval
      parameters:
        - in: body
          required: true
          name: data
          schema:
            $ref: '#/components/schemas/Pereval'

        - in: path
          required: true
          name: id
          schema:
            type: string
          description: id объекта Pereval

      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pereval'
          description: ''
      tags:
        - perevals

components:
  schemas:

    AppUser:
      type: object
      required:
        - e-mail
        - lastname
        - firstname
        - surname
        - phone
      properties:
        e-mail:
          type: string
          format: email
          title: Почта
          maxLength: 150
          example: mail@mail.ru
        lastname:
          type: string
          title: Фамилия
          maxLength: 20
          example: Иванов
        firstname:
          type: string
          title: Имя
          maxLength: 20
          example: Иван
        surname:
          type: string
          title: Отчество
          maxLength: 20
          example: Иванович
        phone:
          type: string
          title: Телефон
          maxLength: 12
          example: '+79009009090'

    Coords:
      type: object
      properties:
        latitude:
          type: number
          format: float
          title: Широта
          maxLength: 10
          nullable: true
          example: 55.555
        longitude:
          type: number
          format: float
          title: Долгота
          maxLength: 10
          nullable: true
          example: 22.222
        height:
          type: number
          title: Высота
          maxLength: 10
          nullable: true
          example: 2500

    Level:
      type: object
      properties:
        winter:
          type: string
          format: choices
          enum:
            - A1-Очень легко
            - A2-Легко
            - B-Средне
            - C1-Сурово
            - C2-Очень сурово
          title: Зима
          maxLength: 20
          nullable: true
        summer:
          type: string
          format: choices
          enum:
            - A1-Очень легко
            - A2-Легко
            - B-Средне
            - C1-Сурово
            - C2-Очень сурово
          title: Лето
          maxLength: 20
          nullable: true
        autumn:
          type: string
          format: choices
          enum:
            - A1-Очень легко
            - A2-Легко
            - B-Средне
            - C1-Сурово
            - C2-Очень сурово
          title: Осень
          maxLength: 20
          nullable: true
        spring:
          type: string
          format: choices
          enum:
            - A1-Очень легко
            - A2-Легко
            - B-Средне
            - C1-Сурово
            - C2-Очень сурово
          title: Весна
          maxLength: 20
          nullable: true

    Images:
      required:
        - image
      type: object
      properties:
        title:
          type: string
          title: Описание
          maxLength: 50
          nullable: true
          example: Описание изображения
        image:
          type: string
          format: uri
          title: Изображение
          nullable: true
          example: https://media.istockphoto.com/id/905167560/ru/%D1%84%D0%BE%D1%82%D0%BE/%D0%B8%D0%B7%D0%B2%D0%B8%D0%BB%D0%B8%D1%81%D1%82%D0%B0%D1%8F-%D0%B4%D0%BE%D1%80%D0%BE%D0%B3%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B0%D0%BB%D0%B0-%D0%BC%D0%B0%D0%BB%D0%BE%D1%8F-%D0%B2-%D1%88%D0%B2%D0%B5%D0%B9%D1%86%D0%B0%D1%80%D0%B8%D0%B8.jpg?s=2048x2048&w=is&k=20&c=05R9e9KMTjRDhPik_DVstTbhTFEwF9r4wsbeqj_LB3E=

    Pereval:
      type: object
      required:
        - beauty_title
        - title
        - other_title
        - connect
        - user
        - coords
        - level
        - images
      properties:
        status:
          type: string
          title: Статус модерации
          default: new
          enum:
            - new
            - pending
            - accepted
            - rejected
        beauty_title:
          type: string
          title: Название перевала
          maxLength: 100
          example: Чике-Таман
        title:
          type: string
          title: Местность
          maxLength: 100
          example: Горный Алтай
        other_title:
          type: string
          title: Округ
          maxLength: 100
          example: Алтай
        connect:
          type: string
          title: Что соединяет
          nullable: true
          example: Долины рек Малый и Большой Ильгумень
        user:
          $ref: '#/components/schemas/AppUser'
        coords:
          $ref: '#/components/schemas/Coords'
        level:
          $ref: '#/components/schemas/Level'
        images:
          $ref: '#/components/schemas/Images'



