# Generated by Django 5.0 on 2023-12-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('fam', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('otc', models.CharField(max_length=20, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=10, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=10, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Зимой')),
                ('summer', models.CharField(choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Летом')),
                ('autumn', models.CharField(choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Осенью')),
                ('spring', models.CharField(choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Весной')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=100, verbose_name='Название перевала')),
                ('title', models.CharField(max_length=100, verbose_name='Местность')),
                ('other_title', models.CharField(max_length=100, verbose_name='Округ')),
                ('connect', models.TextField(blank=True, verbose_name='Что соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('PND', 'Принято в работу'), ('ACT', 'Одобрено'), ('RJT', 'Отклонено')], default='NEW', max_length=3, verbose_name='Статус проверки')),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.coords', verbose_name='Координаты')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.level', verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_pass.appuser', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пометка')),
                ('image', models.TextField(null=True, verbose_name='Ссылка на изображение')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountain_pass.pereval', verbose_name='Перевал')),
            ],
        ),
    ]
