# Generated by Django 5.0 on 2023-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Почта'),
        ),
    ]
