# Generated by Django 5.0 on 2023-12-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Координат', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='pereval',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевалы'},
        ),
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Долгота'),
        ),
    ]
