# Generated by Django 5.0 on 2023-12-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0002_alter_appuser_options_alter_coords_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Осенью'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Весной'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Летом'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, choices=[('A1', 'Очень легко'), ('A2', 'Легко'), ('B', 'Средне'), ('C1', 'Сурово'), ('C2', 'Очень сурово')], max_length=2, verbose_name='Зимой'),
        ),
    ]
