# Generated by Django 5.0 on 2023-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(max_length=5, verbose_name='Высота'),
        ),
    ]
