# Generated by Django 5.0 on 2023-12-25 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0003_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='coords',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='mountain_pass.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='mountain_pass.level', verbose_name='Уровень'),
        ),
    ]
