# Generated by Django 5.0 on 2023-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0003_alter_coords_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
    ]
