# Generated by Django 5.0 on 2023-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0004_alter_coords_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новое'), ('PND', 'Принято в работу'), ('ACT', 'Одобрено'), ('RJT', 'Отклонено')], default='NEW', max_length=3, verbose_name='Статус проверки'),
        ),
    ]
