# Generated by Django 5.0 on 2023-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0005_alter_pereval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(blank=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Долгота'),
        ),
    ]
