# Generated by Django 5.0 on 2023-12-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0006_alter_coords_height_alter_coords_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(max_length=10, verbose_name='Долгота'),
        ),
    ]
